### ISSUE TITLE
Thanks for making this!

### ISSUE THREAD

**Issue by KraXen72** [probablykasper/vite-plugin-electron-x#1]
I was using https://github.com/jctaoo/elecrun in my project, but the documentation is really bad and half in chinese, so i had to go off of a few examples and only barely got it working.

Is this project a replacement for https://github.com/jctaoo/elecrun? if not, which features would you say are missing?

Thanks.

**Comment by kasper9n** [comment]
Thanks! Didn't know about elecrun till now, but I think this plugin should cover most of what it does. Anything you need in particular?

**Comment by kasper9n** [comment]
There are nice auto generated docs on paka.dev: https://paka.dev/npm/vite-plugin-electron-x
